[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
evm_version = "cancun"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Use: forge coverage --no-match-coverage "test/mocks/" to exclude mocks

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
